In [1]:
from keras.datasets import mnist
import numpy as np
import matplotlib.pyplot as plt

%matplotlib inline

(x_train, y_train), (x_test, y_test) = mnist.load_data()

images = x_train
labels = y_train

  # one hot encode target values
#y_train = to_categorical(y_train)
#y_test = to_categorical(y_test)

In [27]:
def relu(x):
    return (x > 0) * x

def relu2deriv(out):
    return out > 0

In [3]:
test_images = x_test
test_labels = y_test

In [5]:
inputs = np.zeros((60000, 784))
for i in range(len(images)):
    inputs[i] = np.concatenate(images[i])
    for j in range(len(inputs[i])):
        inputs[i][j] /= 255


test = np.zeros((10000, 784))
for i in range(len(test_images)):
    test[i] = np.concatenate(test_images[i])
    for j in range(len(test[i])):
        test[i][j] /= 255



In [168]:
weights_1 = np.random.rand(16, 784)/10 # Веса от входному слою, к скрытому слою из 16 нейронов
weights_2 = np.random.rand(10, 16) # Веса от скрытого слоя к выходному слою
print(weights_1)

[[0.04758612 0.07360592 0.05329361 ... 0.08924899 0.08659656 0.02492939]
 [0.00125963 0.05726402 0.03981074 ... 0.04790714 0.01709821 0.09470576]
 [0.06507048 0.09324536 0.03846057 ... 0.05217756 0.0545446  0.0412135 ]
 ...
 [0.05238059 0.060852   0.07674754 ... 0.04201625 0.09728484 0.09242763]
 [0.08021937 0.07318573 0.00391991 ... 0.07438519 0.01793049 0.01709303]
 [0.09275556 0.06728746 0.0005179  ... 0.02323036 0.06129973 0.03606209]]


In [ ]:
weights_1 = np.random.rand(784, 16)/10 # Веса от входному слою, к скрытому слою из 16 нейронов
weights_2 = np.random.rand(16, 10) # Веса от скрытого слоя к выходному слою
print(weights_1)

[[0.04758612 0.07360592 0.05329361 ... 0.08924899 0.08659656 0.02492939]
 [0.00125963 0.05726402 0.03981074 ... 0.04790714 0.01709821 0.09470576]
 [0.06507048 0.09324536 0.03846057 ... 0.05217756 0.0545446  0.0412135 ]
 ...
 [0.05238059 0.060852   0.07674754 ... 0.04201625 0.09728484 0.09242763]
 [0.08021937 0.07318573 0.00391991 ... 0.07438519 0.01793049 0.01709303]
 [0.09275556 0.06728746 0.0005179  ... 0.02323036 0.06129973 0.03606209]]


In [144]:
alpha = 0.001

In [12]:
def predict(data, weight_1, weight_2):
    return np.dot(weight_2, np.dot(weight_1, data))

In [10]:
def proccess_labels(labels):
    out = np.zeros((len(labels), 10))
    for i in range(len(out)):
        out[i][labels[i]] = 1
    return out

In [11]:
new_labels = proccess_labels(labels)
new_labels[0]

array([0., 0., 0., 0., 0., 1., 0., 0., 0., 0.])

In [171]:
def train(epochs, true_labels):
    global weights_1, weights_2
    for iteration in range(epochs):
        layer_2_error = 0
        for i in range(2):
            layer_0 = inputs[i]
            layer_1 = relu(np.dot(weights_1, layer_0))
            layer_2 = np.dot(weights_2, layer_1)

            #layer_2_error += np.sum((layer_2 - true_labels[i]) ** 2)
            layer_2_delta = layer_2 - true_labels[i]
            layer_1_delta = layer_2_delta.dot(weights_2.T)
            print(alpha * layer_2.dot(layer_2_delta))
            print(alpha * layer_1.T.dot(layer_1_delta))
            print(layer_2_delta.T.shape)
            #print(layer_2_delta)
            #print(layer_2)
            #print(np.dot(weights_1, layer_0))
            #print(weights_1)
            #print(weights_2)
            #print(layer_0)
            #weights_2 -= alpha * layer_2.dot(layer_2_delta)
            #weights_1 -= alpha * layer_1.dot(layer_1_delta)
        #print(f'Error: {layer_2_error}')

In [172]:
train(10, new_labels)

ValueError: shapes (10,) and (16,10) not aligned: 10 (dim 0) != 16 (dim 0)

In [15]:
predict(test[1], weights_1, weights_2)

array([4.67605764, 5.29175452, 4.49969179, 5.4353332 , 4.00039347,
       3.86008087, 4.39995793, 5.79397606, 4.51901898, 4.79520541])